### ISSUE TITLE
Une variable $userId peut être assignée un customerId au lieu d'un userId

### ISSUE THREAD

**Issue by jessyjr97** [yjacques940/customerManager#154]
Dans la fonction _HasDoneTheSurvey()_ et _MedicalSurveyUpdate()_, les variables **$userId** et **$_SESSION['TempCustomerId']**, utilisées de nombreuses fois un peu partout dans le code peuvent être assignées un _customerId_ ou encore un _userId_.

Un utilisateur standard va normalement être assigné un _userId_, mais un employé peut souvent envoyer un URI comprenant un _customerId_, qui sera assigné dans la variable **$userId**.

**$userId** est utilisé dans des fonctions utilisant un _customerId_ et dans d'autres fonctions utilisant un _customerId_, donc plusieurs fonctions auront des résultat inattendus.

Extraits de code:
_HasDoneTheSurvey()_
`$userId = isset($_GET['idCustomer']) ? $_GET['idCustomer'] : $_SESSION['userid'];`
`$_SESSION['TempCustomerId'] = $userId;`
_MedicalSurveyUpdate()_
`$userId = isset($_SESSION['TempCustomerId']) ? $_SESSION['TempCustomerId'] : $_SESSION['userid'];`

**Comment by yjacques940** [comment]
$userId = isset($_SESSION['TempCustomerId']) ? GetCustomerUserId($_SESSION['TempCustomerId']) : $_SESSION['userid'];

function GetCustomerUserId($customerId)
{
