### ISSUE TITLE
En tant que client, je ne peux pas consulter les informations de mes rendez-vous

### ISSUE THREAD

**Issue by yjacques940** [yjacques940/customerManager#160]
Les permissions ne sont aps correctes, seulement un admin peut accéder aux infos d'un rendez-vous. Le client dervait pouvoir voir son propre rendez-vous

**Comment by Agagnon01** [comment]
Haha, tu peux me l'assigner mais j'ai un doute que je ne la ferai pas.

**Comment by Agagnon01** [comment]
@yjacques940
