### ISSUE TITLE
Lors de la création d'un client, on peut inscrire une date de naissance dans le futur

### ISSUE THREAD

**Issue by jessyjr97** [yjacques940/customerManager#175]
Affecte création côté admin et côté inscription

**Comment by yjacques940** [comment]
Il faudrait peut-être mettre un masque à la place, je crois que ce serait beaucoup plus simple que de mettre un calendrier où on doit cliquer et revenir quelques années en arrière. Une personne qui a 80 ans va trouver ca long retourner en arrière avec le calendrier. Donc en mettant une textbox avec un masque, on peut gérer le format d'entrée de la date de naissance pour l'enregistrer en DateTime dans la base de données
