### ISSUE TITLE
En tant qu'utilisateur, je veux pouvoir modifier mon mot de passe afin d'utiliser un nouveau mot de passe pour me connecter

### ISSUE THREAD

**Issue by yjacques940** [yjacques940/customerManager#27]
- [ ] Une fenêtre de modification de mot de passe doit être affichée lors du clic du bouton de modification de mot de passe

- [ ] L'utilisateur doit entrer l'ancien et le nouveau mot de passe, puis une confirmation du mot de passe

- [ ] L'utilisateur doit entrer son adresse courriel

- [ ] L'utilisateur doit confirmer le changement par courriel

**Comment by iamkinetic** [comment]
Votre façon d'écrire vos issues est très intéressante!
