### ISSUE TITLE
En tant qu'utilisateur, je veux pouvoir choisir mon traitement afin que les thérapeutes me traitent correctement

### ISSUE THREAD

**Issue by jessyjr97** [yjacques940/customerManager#55]
- [x] Le nom des types de traitements doivent être affichés dans une liste
- [x] Lorsque je sélectionne un traitement, celui-ci s'affiche
- [x] Si c'est un traitement de pierres chaudes ou d'1h30, proposer d'appeler ou de faire une demande de réservation

**Comment by yjacques940** [comment]
Bloqué par #70
